name: Continuous Deployment
on: 
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      SOURCE_DIR: "build/"
    
    steps:

      - uses: actions/checkout@v1
    
      - name: Install dependencies
        run: npm install
    
      - name: Build
        run: npm run build
    
      - name: Deploy staging
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
        with:
          source: "build/"
          target: "/usr/share/nginx/html/app"
    
      - name: Deploy production
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
        with:
          source: "build/"
          target: "/usr/share/nginx/html/app"
          args: --acl public-read --follow-symlinks --delete